### ISSUE TITLE
Can I export the map as a png or jpeg file?

### ISSUE THREAD

**Issue by wuqi** [ofrohn/d3-celestial#1]
Sorry for my poor English.
Thanks for the great work,I like the map ,is there someway to export the celestial map to a jpeg or png file?It will be easier to print and see.

**Comment by ofrohn** [comment]
Hi, thanks for the interest!
If you use a desktop computer, try right-clicking on the image and 
choose "save image as.." or the like. That should save a png file on the 
disk. For printing, make sure it is large enough so the aliasing doesn't 
show.

Cheers, Olaf

Am 21.05.2016 um 18:06 schrieb wuqi:

**Comment by wuqi** [comment]
Thank you ,I get it
