### ISSUE TITLE
redraw() method does nothing

### ISSUE THREAD

**Issue by donjajo** [ofrohn/d3-celestial#104]
Hi,

I am not sure I am doing this the right way, I probably might be missing something. I wish to pass the coordinates on runtime, I am using this:

```
Celestial.location(5.0, 6.0)
Celestial.redraw()
```

But it does nothing, I have tried other methods and then `redraw()` but nothing happens. How to I set options on runtime?

**Comment by ofrohn** [comment]
Celestial.location  has the parameters [lat, long} and optionally timezone.
So try ``Celestial.location([5.0, 6.0])`` to set 5° N / 6° E as your location. If you don't set a timezone, it will be set automatically.

**Comment by donjajo** [comment]
Thank you. The problem is not the `location` method. Thanks for clearing it up, I have passed an array instead, but the `redraw` method does nothing. I am using this on React component, and implemented well as I have with other nonReact libraries.

**Comment by donjajo** [comment]
Figured it. I used `Celestial.apply()` method to make changes on runtime 

Thanks
