### ISSUE TITLE
Expanding time range 

### ISSUE THREAD

**Issue by alexandrudragos** [ofrohn/d3-celestial#11]
Hello,
Is there a way to make the time range of the projections beyond 10 years from current year? Does it have to be backed by a specific database?

Thank you!

**Comment by ofrohn** [comment]
No, that was an arbitrary, hardcoded time range. As a quick fix I´ve changed it to +/- 10 years from the *displayed* date, so you can jump in 10-yr steps. Caveat is that the planetary positions are only accurate from 1800 to 2050.
I can make the time range configurable in the config, if you´d prefer that.

**Comment by alexandrudragos** [comment]
Hello again,

Thank you for your quick answer! 

Do you think you can help me out by making it configurable in the config? I am a bit lost..hehe
Or you can tell me how to do that.
That you mean a lot. Thank you in advance!

**Comment by alexandrudragos** [comment]
Thank you! That should do it!

**Comment by ofrohn** [comment]
You´re welcome!
