### ISSUE TITLE
[Question] Serverside render

### ISSUE THREAD

**Issue by codihaus** [ofrohn/d3-celestial#111]
Hello,

I'm working on a project where I have to render the star map on the server-side, so I'm considering several options to achieve, I hope that you guys can point me out if my method is correct.

1/ Method 1: Server-side rendering

- On the frontend, after the user selects the options, we will have the global var to store the config.
- We will POST the JSON to server
- Server receive JSON and call starmap function to directly export to SVG object

So, the question for this method is: how can we get the options to store as JSON file? What is the function to render the SVG file object from JSON on the server?

2/ Method 2: Client-side rendering

- On the frontend, we will directly export current options as SVG, but not download it, we will store that object in a variable and POST the SVG as base64 to server.
- Server will add base64 image (SVG in this case) to canvas to render

So, my question is:

- How can we export the SVG without download it but storing it in a variable?

Thank you very much for this awesome lib!

**Comment by avachasov** [comment]
Hi, you can easy get the SVG on client side using 'exportSVG' function.
Here is working example:

**Comment by codihaus** [comment]
Hi @avachasov 

I have achieved it. Thank you much!
