### ISSUE TITLE
"center" should optionally not override "geopos" in config

### ISSUE THREAD

**Issue by DanielO** [ofrohn/d3-celestial#15]
Hi,
I want to have geopos set to produce a horizon, but want the (initial) center to be something else.

I tried working around it by calling Celestial.rotate after drawing but it then starts there but straight after it moves the center to geopos.

**Comment by DanielO** [comment]
Do you have any suggestions where to start looking in the code?

Thanks.

**Comment by ofrohn** [comment]
I already did it, yesterday. It wasn't as bad as I thought...
The latest version has a new config-parameter named "follow" with two options so far: 
"zenith" (default) keeps the prevoius behavior to always center the map on the zenith if location is enabled
"center" leaves the map centered on whatever you put in the center parameter.

So try ``follow: "center"`` That's probably what you were looking for.

**Comment by DanielO** [comment]
Ah, very nice thank you!

I updated my demo so now it doesn't float around so much.. Now to make it 10x faster ;)
