### ISSUE TITLE
Double clicking on map produces "Cannot read property '0' of undefined" error

### ISSUE THREAD

**Issue by DanielO** [ofrohn/d3-celestial#16]
Hi,
If I double click on the map I get this error in the console..

```
d3.min.js:2 Uncaught TypeError: Cannot read property '0' of undefined
    at Function.t.rotate (d3.min.js:2)
    at HTMLCanvasElement.<anonymous> (celestial.min.js:6)
    at HTMLCanvasElement.t (d3.min.js:1)
    at o (d3.min.js:3)
    at Object.u (d3.min.js:3)
    at Rn (d3.min.js:1)
    at Tn (d3.min.js:1)

```

If I look at Function.t.rotate..
```
                    if (r !== t) {
                        r.each("start.zoom", function() {
                            this.__chart__ && (y = this.__chart__),
                            p.rotate(y.r).scale(y.k),
                            l(e)
                        }).tween("zoom:zoom", function() {
```

The object 'y' has x, y & k properties but not r so d3.rotate gets fed an undefined and chokes.

Not sure if this is related to issue #10 or something with similar symptoms.

**Comment by ofrohn** [comment]
Hint: If you delete the min from d3 and celestial where you include  them in the html, as in  
d3.min.js -> d3.js and celestial.min.js -> celestial.js
you get the proper function names, not minified single-letter ones!

**Comment by ofrohn** [comment]
As for the error, it's possible that it's relatet to #10, but when I try it, the map keeps working despite the error, and on the next move zooms in a bit. 
So I just need to properly handle the double click event and zoom in one step straight way, the thing it wants to do anyway...

**Comment by DanielO** [comment]
Interesting - for me it does not zoom in when I double click. I am using Chrome 67.0.3396.99 on OSX FWIW.

**Comment by ofrohn** [comment]
Turns out the double click event was already handled, but differently in d3 and the zoom module I use d3.geo.zoom, that clashed with each other. Simply deactivating one and zooming manually did the trick.

If you pull the latest version, it should work now. I also tweaked the zoom levels for the + / - buttons a bit, I think it's less tedious now.

**Comment by DanielO** [comment]
Looks good, thanks.
