### ISSUE TITLE
How can I add some other projections?

### ISSUE THREAD

**Issue by wuqi** [ofrohn/d3-celestial#2]
I try to add some polyhedron projections like http://bl.ocks.org/mbostock/4458680  and https://bl.ocks.org/espinielli/5676160  , but it only shows part of them.

code like
`if(projection == "butterfly"){
      var proj = d3.geo.polyhedron.butterfly();
      forward =  function(λ, φ) {
        var coords = proj([-λ, φ]);
        return coords;
      };
      forward.invert = function(x, y) {
        var coords = proj.invert(x, y);
        coords[0] *= -1;
        return coords;
      };
      return d3.geo.projection(forward);
  }`

**Comment by ofrohn** [comment]
Have you tried adding butterfly to the projection definitions in config.js? With this line
`  "butterfly": {n:"Butterfly", arg:null, scale:31, ratio:1.1, clip:true},`
and your code added to projections.js the whole thing is visible at least. It looks strange & panning doesn't work, so that would still need some work.

**Comment by ofrohn** [comment]
Dunno why github thinks my previous commits reference your issue

**Comment by florsignol** [comment]
Hi, I'm trying to add my own projection, I need a Cassini projection: https://en.wikipedia.org/wiki/Cassini_projection

Doing something like this doesn't work:
```
var cassini = d3.geo.equirectangular().rotate([0, 0, 90]).translate([config.width / 2, config.width]);
// var cassini = d3.geo.equirectangular();

var config = { 
  projection: cassini
...
}
```

**Comment by ofrohn** [comment]
@florsignol To use a projection you first need to define it. The best place to do that is in d3.geo.projections. To test it I had to actually do it, so I've just added the hemispherical version to it. And Cassini isn't just Equirectangular turned 90 degrees, it's a bit more complicated than that. The elliptical version is still more complicated, I'll leave that tro you...
Lastly you need to set the basic parameters for the projection in config.js, in the projections object

**Comment by ofrohn** [comment]
The app has reached a state where it is difficult to add features without breaking something else. So I won't, apart from error corrections.
When I find the time, I'll  do a rewrite, probably with the latest version of d3. It will be announced in the readme when it's ready.
