### ISSUE TITLE
Rotate using Celestial.date() ?

### ISSUE THREAD

**Issue by Picorete** [ofrohn/d3-celestial#20]
Well, im using my own datepicker, but when i pass the date with celestial.date() the map don't rotate. How can i make they rotate only with new date :(

**Comment by rudjuh** [comment]
Yeah i have the same problem. Location = true. Someone?

**Comment by ofrohn** [comment]
Celestial.date() should take any valid javascript date object. provided you set location = true, as noted above.
Can you show some code snippet if you need further help?

**Comment by Picorete** [comment]
See the example here: https://www.ricardougas.com/celestial/ , Run Celestial.date() in the Chrome Console.
It's fine, gets the date, and the original datepicker to, but i'm using my own datepicker, and what i did was this: 

`$('tbody').on('click', function(){
    setTimeout(function(){
        var d = new Date($('#date').val());
        Celestial.date(d);
        $('#day-right').click();
    }, 100);
    
});`

I simulate a click on the original Celestial Datepicker, the button "Next Day" in that way the date update, but then i lose the location, and put the map in the center again but the date is fine. I wanna run just 'Celestial.date()' and the map just rotate with new date, and not change the actually location :(

**Comment by rudjuh** [comment]
> See the example here: https://www.ricardougas.com/celestial/ , Run Celestial.date() in the Chrome Console.
> It's fine, gets the date, and the original datepicker to, but i'm using my own datepicker, and what i did was this:
> 
> `$('tbody').on('click', function(){
> setTimeout(function(){
> var d = new Date($('#date').val());
> Celestial.date(d);
> $('#day-right').click();
> }, 100);
> 
> });`
> 
> I simulate a click on the original Celestial Datepicker, the button "Next Day" in that way the date update, but then i lose the location, and put the map in the center again but the date is fine. I wanna run just 'Celestial.date()' and the map just rotate with new date, and not change the actually location :(

It is a temporary solution. But it just getting the next day and not the right date selected. Someone has a solution here?

**Comment by Picorete** [comment]
> @Picorete I tweaked your solution. I set the date and then clicked the next day.
> 
> ```
>     $( "#color, #new-date" ).change(function() {
>         let bg = $('#color').val();
>         let d = $('#new-date').val();
>         updateMap(bg, d)
>     });
> 
>     function updateMap(bg, d) {
>         let config = {
>             center: [14,56,0],
>             background: {
>                 fill: bg
>             }
> 
>         };
>         // Correct javascript date format
>         let date = new Date(d);
>         // Set the Celestial date
>         Celestial.date(date);
> 
>         // Go right and left for the animation bug
>         $('#day-right').click();
>         $('#day-left').click();
> 
>         Celestial.apply(config);
>     }
> ```
> If you do this it will set the date you selected and it will animate.

Yeah if you see my code, i was doing that, set the date, and in my case just click one day more. The think is, if you have a location in the map, ( for example Miami Usa = [25.77481, -80.19773, 0]) when i set the date, and simulate the click, the map go back to the center, so they lose the Miami location, 
even though the date is fine.

**Comment by rudjuh** [comment]
@Picorete Did you already found a solution?

**Comment by ofrohn** [comment]
Sorry my answer is pretty late, but I´m desperately lacking time a the moment.
Anyway, this looks like a genuine error in the source, I can maybe look into it over the next few days

**Comment by rudjuh** [comment]
@ofrohn No problem! Take your time.

**Comment by rudjuh** [comment]
@ofrohn I have an issue setting the date on march 2000. It says: Cannot read property 'getTimezoneOffset' of null and Uncaught TypeError: Cannot read property 'setTime' of null. On every date on march 2000 it gives me an error. All the other dates are working.

**Comment by Picorete** [comment]
> @ofrohn No problem! Take your time.

I see what is the problem bro! , when you change with Celestial.rotate(lon, lat) , the map change, but! , the text of the id="celestial-form" ( the default form ), the texts of lat and lon, they dont change, so, when you change with Celestial.rotate, change that values too, like this: 

```
$('#lat').val(latitude);
$('#lon').val(longitude);
```

in that way, this will be okay 

```

 Celestial.date(date);
        // Go right and left for the animation bug
        $('#day-right').click();
        $('#day-left').click();
```

**Comment by ofrohn** [comment]
I've refactored a bit and added the new function skyview, which works independent of any form or location settings and does this: 
* `Celestial.skyview({date:<date object>, location:[lat, lon]})`  
  Show the current celestial view for one specific date and/or location, 
  independent of form fields, both parameters are optional  
  called w/o parameter returns {date, location} in same format.  
  _date_: javascript date-object  
  _location_: [latitude, longitude] array in degrees   
I hope that will resolve any strange behavior the map might exhibit.

**Comment by zzadik** [comment]
@ofrohn Thank you for adding this function. Exactly on time for me.
I've integrated the module in my React app, and have the following code:

```
const` Celestial = window.Celestial;

    Celestial.skyview({
      date: new Date('December 17, 1995 03:24:00'),
      location: [40.712776, -74.005974]
    })

```

I get "Celestial.skyview is not a function" error.
Any idea how to call the new function?
I must add that using Celestial with other functions works great.

Thanks in advance!
