### ISSUE TITLE
Mapping screen coordinates

### ISSUE THREAD

**Issue by DanielO** [ofrohn/d3-celestial#21]
Hi,
I'd like to display the current equatorial coordinates of the mouse pointer so when a user is looking for features in data they can note down the position.

I couldn't see an existing function to do this but perhaps I am missing something that already exists in d3.

Any pointers much appreciated - thanks.

**Comment by ofrohn** [comment]
Every map projection in d3 has an invert function that takes [x, y] screen coordinates and returns map coordinates.
It is accessible as ```Celestial.mapProjection.invert([x,y])```
That should do what you need.

**Comment by DanielO** [comment]
Oops I only just got around to trying this..
```
  function getClickPosition(e) {
    var inv = Celestial.mapProjection.invert([e.screenX, e.screenY]);
    if (inv === undefined)
      return;
    document.getElementById('coords').innerHTML = sprintf("%.2f x %.2f -> %.2f x %.2f",
							  e.screenX, e.screenY,
							  inv[0], inv[1]);
  }
  document.getElementById ('celestial-map').addEventListener('click', getClickPosition, false);
```

However I find it reports the same value for a given screen coordinate regardless of how the display has been dragged around.

Do I need to add or subtract the current centre from them to get the right value?

**Comment by ofrohn** [comment]
Using pageX and pageY instead of screenX/Y it worked perfectly for me! It gives the coordinates relative to the event's source element instead of the whole screen.
A click outside of the projected map causes an error and doesn't change the value. Depending on where the browser window is, that might be the cause of the observed behavior.

**Comment by ofrohn** [comment]
Correction. pageX/Y needs the top left position of the map subtracted to work, so your function would be:
```js
  function getClickPosition(e) {
    var map = document.getElementById ('celestial-map');
    var inv = Celestial.mapProjection.invert([e.screenX, e.screenY]);
    if (inv === undefined || isNaN(inv[0]))
      return;
    document.getElementById('coords').innerHTML = sprintf("%.2f x %.2f -> %.2f x %.2f",
							  e.pageX - map.offsetLeft, e.pageY - map.offsetTop,
							  inv[0], inv[1]);
  }
```
Also, invert returns [NaN, NaN] if the screen coordinates are outside the projected map area. I blame d3.js for that.

**Comment by DanielO** [comment]
Thanks I tried that but I found it didn't line up with the limits of the projection so I dug a bit more and ended up with:

````javascript
    var map = document.getElementById('celestial-map');
    var x = e.offsetX;
    var y = e.offsetY;
    var inv = Celestial.mapProjection.invert([x, y]);
    if (inv === undefined || isNaN(inv[0]))
      return;
````
