### ISSUE TITLE
About projection shape

### ISSUE THREAD

**Issue by sunny923** [ofrohn/d3-celestial#22]
I want to show star map inside my own svg, because I need a proper heart shape design and inside that a star map. But in this just Bonne projection which is not look like a heart. Is there any way to add a proper heart shape projection?

**Comment by ofrohn** [comment]
I don't know any other heart shaped projection, but Bonne has an additional parameter that allows to manipulate the shape of the outline. I wanted to make that user configurable for a long tme, just haven't got around to it jet.
Anyway, for some reason I dont remember I chose the shape you saw, but with a bit of tweaking it looks much more heart shaped. Check out the latest version, online here http://ofrohn.github.io/celestial-demo/viewer.html

**Comment by sunny923** [comment]
ok thank you so much
