### ISSUE TITLE
Import Celestial as Library

### ISSUE THREAD

**Issue by GuLinux** [ofrohn/d3-celestial#23]
Hi,
I find the project quite interesting, and I'd like to integrate it with my astrophotography application: https://github.com/GuLinux/StarQuew .
However I can't seem to be able to import the library, not with ES6 `import`, nor with `require`, apparently `celestial.js` doesn't export anything.
Looking at the source, I found a declaration I'm not familiar with (starting with a `!`, then assigning `this.Celestial = this`, although I'm not sure what the `this` object should be in this case).

Could you make the js a bit more "import friendly"?
Thanks,
Marco

**Comment by GuLinux** [comment]
Scrap that, I was able to circumvent the issue using a different build command on my library.
FYI, I've created a React wrapper for Celestial here: https://github.com/GuLinux/d3-celestial-react

Not very feature complete at the moment, but it's a start :)

**Comment by alexandervlpl** [comment]
@GuLinux : what was the build command that worked for you?
