### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'name' 

### ISSUE THREAD

**Issue by GuLinux** [ofrohn/d3-celestial#26]
Hi,
this is probably an issue I only see because my React wrapper around d3-celestial has to pass through babel/webpack, with more strict proptypes checks.
I get this error when I load a map:
```
index.dev.js:3791 Uncaught TypeError: Cannot assign to read only property 'name' of function 'function kepler(date) {
          dates(date);

          if (id === "sol") {
            dat.x = 0;
          ...<omitted>... }'
    at Kepler (index.dev.js:3791)
    at getPlanets (index.dev.js:1436)
    at index.dev.js:499
    at Object.<anonymous> (index.dev.js:9022)
    at Object.t (index.dev.js:8472)
    at XMLHttpRequest.i (index.dev.js:8985)
```

It would seem caused by the overwriting of the name property with a function.

Applying the following patch mitigates the issue:
```
--- libs/celestial.js-orig	2018-11-30 13:20:47.632758430 +0000
+++ libs/celestial.js	2018-11-30 13:28:57.966220021 +0000
@@ -2625,6 +2625,10 @@
     return kepler;
   };
 
+  Object.defineProperty(kepler, 'name', {
+    writable: true,
+  });
+
   kepler.name = function(_) {
     if (!arguments.length) return name; 
     name = _;
```

However i believe a better fix would be to refactor this, and use a different name for the `name` function, for instance `getName`

**Comment by ofrohn** [comment]
My bad for using a reserved word. I´ve renamed the parameter to Name. 
Until a bigger refactoring...
