### ISSUE TITLE
Allow to set zoom programmatically

### ISSUE THREAD

**Issue by GuLinux** [ofrohn/d3-celestial#27]
It would be nice to be able the desired zoom level (possibly in arcminutes) in order to allow visualizing a certain predefined area instead of the full map at startup.
Updating zoom through the config should also be allowed using the `apply` function.
Another related desired change would be to have the `ZOOMEXTENT` property configurable.

**Comment by ofrohn** [comment]
You can set zoom during runtime with the zoomBy(factor) function, where factor is a float that changes the current zoom level  by zoom * factor.
Setting zoom in config and maybe ZOOMEXTENT is added to the ToDo

**Comment by ofrohn** [comment]
OK, that was easier than I thought, so I just put 'zoomextend' and 'zoomlevel' in the config object. See readme for details, the initial zoom level is simply 100% * zoomlevel

**Comment by Daxtermania** [comment]
Hello,
I am trying to use it but it doesn't work.
Is this the correct use?

```
cfg.zoomlevel = 2;
Celestial.apply(cfg);
```

Thanks,
