### ISSUE TITLE
Map customization not working

### ISSUE THREAD

**Issue by rstilora** [ofrohn/d3-celestial#28]
Hi 
Thanks for resources.
Can you please tell me how to rotate map.
I am trying to redraw map with different parameter values but not working. 
Celestial.redraw({transform:equatorial|ecliptic|galactic|supergalactic}) Not Working

Can you please help me.

**Comment by ofrohn** [comment]
Sorry for the late comment, I was terribly busy for the last few months.
What you are trying to do works by specifying one specific coordinate transform as a string
```js 
Celestial.redraw({"transform": "galactic"});
```
You're doing it this way?
