### ISSUE TITLE
Adding another data file

### ISSUE THREAD

**Issue by Jaacky** [ofrohn/d3-celestial#3]
Hi,

I'm trying to add another data file by doing this:
Celestial.add({file:<path>, type:"dsos", ...});

What format should the file be in? I tried the same format that the other data files are in (like stars.6.json) 

And what should the callback do? I tried having the callback call Celestial.redraw so that it can update the map.

In both cases, the map is either not updated or I'm getting the error t.redraw() is not a function.
Some pointers/direction would be great!

Thanks

**Comment by Jaacky** [comment]
Nvm figured it out

**Comment by puziip** [comment]
Jaacky - I am having the same issues...would be great if you could share your solution?

Thanks
P.

**Comment by ofrohn** [comment]
I have added a howto section to the readme with a simple example of addig data. Hope that helps!

**Comment by puziip** [comment]
Great - many thanks Olaf - I have the bare bones of it working now!
