### ISSUE TITLE
Zoom and pan without changing center

### ISSUE THREAD

**Issue by timbeccue** [ofrohn/d3-celestial#33]
Really like this star map!

Feature request: I'd like to be able to zoom in and pan around, all without changing the center of the map. The idea is to explore what's currently up in the night sky, so fixed center coordinates (over short timescales) is important for keeping the map accurate with a fixed observing location. 

It would work perfectly fine if the projection didn't change while panning, as if the map were printed on paper and a camera moved closer to zoom and side-to-side to pan. In other words, I'm not too concerned with correcting edge distortion. 

Does this sound doable?

**Comment by ofrohn** [comment]
Zoom is implemented as such, it zooms in around the current center. Panning is implemented by changing the current center you are looking at, so I don't think it works otherwise.
I'm not sure what that would be useful for, since panning by definition means you are looking at a different center, if you want to have the possibility to restore a previous state you can always store and restore coordinates.

**Comment by ofrohn** [comment]
OK, that was easier than I thought, so I just put 'zoomextend' and 'zoomlevel' in the config object. See readme for details, the initial zoom level is simply 100% * zoomlevel

**Comment by timbeccue** [comment]
Here is an example (using d3) of the zoom/pan functionality I'm imagining: 
https://bl.ocks.org/mbostock/d1f7b58631e71fbf9c568345ee04a60e

Here is another example of something similar to what I'm hoping to make: 
https://www.skymaponline.net/

I find this type of panning more useful than the current method for two reasons. One is that it provides a simple way to ensure you cannot pan past the current visible horizon. The other is that I need to keep a fixed orientation (to prevent panning from inadvertently rotating the display), but if I set orientationfixed:true and bring a pole anywhere close to the center, the projection will spin around wildly (which seems like an unavoidable mathematical property of this setup).

Hopefully this helped clarify things a bit. Again, I really appreciate what you've done so far; thank you!

**Comment by ofrohn** [comment]
The app has reached a state where it is difficult to add features without breaking something else. So I won't, apart from error corrections.
When I find the time, I'll  do a rewrite, probably with the latest version of d3. It will be announced in the readme when it's ready.
