### ISSUE TITLE
Question about use

### ISSUE THREAD

**Issue by SquilliamWallace** [ofrohn/d3-celestial#34]
my apologies for leaving this as an issue, but i wasn't sure how else to get in touch with you. I noticed you use a BSD license, which frankly, i am unfamiliar with, and just wanted to make sure that it would be okay to use this for a senior design project i'm working on in college. We are going to be working with radio astronomy and this is perfect for our purposes, to be able to see what objects will be in the sky at a certain time. Please let me know, and thank you.

**Comment by ofrohn** [comment]
Yes, of course you can use it, with attribution (link to this repository)
