### ISSUE TITLE
How to build files into Celestial.js or celestial.min.js?

### ISSUE THREAD

**Issue by zzulanas** [ofrohn/d3-celestial#35]
Hi there, I was doing some experimenting around in the code and I was wondering how I build all the individual files into the celestial.js main file? I've been editing the main file to test but I want to actually change each individual file and rebuild. I couldn't find any npm tasks to do this, so I was wondering how you did it.

Thanks

**Comment by ofrohn** [comment]
The main directory contains a make.js file. With dev-dependencies installed, a call to node make.js should produce a celestial.js and celestial.min.js in the same directory, if it compiles.
