### ISSUE TITLE
Add new points and resize

### ISSUE THREAD

**Issue by roquasr** [ofrohn/d3-celestial#36]
Hello, thank you for d3-celestial… It’s awesome!!!

I am trying to add new points to the map. My purpose is to show the antisolar point (Earth Shadow) and the geo belt. I am following the instructions that you left in the readme but I am having some troubles. I suppose that it is my failure but I do not understand why.
To add both figures, I am writing them in the GeoJSON. The code of the antisolar point in the geoJson is:
```
{"type": "Feature",
   "id": "GC",
   "properties": {
     "name": "",
     "desig": "PN",
     "type": "antisolarshadowpoint",
     "mag": 3,
     "dim": "60"
   },
   "geometry": {
     "type": "Point",
     "coordinates": [123.60469651,19.8523322646]
  }},
```

So, I modified the config.js and I inserted the object antisolarshadowpoint:

`antisolarshadowpoint: {shape: "bigCircle", fill: "#ffcccc", opacity: 0.5},`

And I also modified canvas.js and I defined bigCircle as:

```
"bigCircle": function(ctx) { //created to add shadow to a point
var s = Math.sqrt(size()), 
      r = s*4; 
      ctx.arc(pos[0], pos[1], r, 0, 2 * Math.PI);
      return r;
  },
```

At the end, I can draw the circle representing the antisolar point, but it doesn’t resize when I do zoom in or zoom out. For the geobelt is the same.

I have two questions:

1- Can I draw the antisolar point and the geo belt in other way (cleaner than I did) or I am using the correct one?

2- How can I do to resize the objects with the zoom in/out?

Many thanks for your help!!!

**Comment by ofrohn** [comment]
Your code looks good, the radius r would need to be dynamically adapted to zoom level.
A call to Celestial.zoomBy() without parameter returns the current zoom level with 1 = 100%

**Comment by roquasr** [comment]
Thank you for your answer, it works! I had to update my library to the v0.6.11version (zoomBy returning the zoom level wasn't included in my old version).

Now I working on the geobelt (a rectangle that represent the geostationary orbit in sky). The idea is to draw the rectangle over the map.

![example1](https://user-images.githubusercontent.com/48351646/58468229-72c4d080-813d-11e9-9e3f-81c699cb3ba5.png)

My problem is that when I move the map and the geobelt must be reprojected, it is wrong painted:

![example2](https://user-images.githubusercontent.com/48351646/58468893-b5d37380-813e-11e9-9ed1-543f911eb8f4.png)

It understand why it happens but I don't know how to implement an easy solution. To paint the rectangle of the geobelt, I have the points of the corners and intermediate points. I project that all points in the map and then, in the canvas function, I connect all points with a line.

```
"belt": function(ctx) {
      var s = Math.sqrt(size()), 
      r = s*4*Celestial.zoomBy();

      //Initial point. Lower Right corner
      ctx.moveTo(pos[2], pos[3]);

      for(var i=4; i<pos.length; i+=2){
        ctx.lineTo(pos[i], pos[i+1]);
      }

      ctx.closePath();
      return r;
    },
```

The problem is that it draws a line from one side of the map to other, but it should stop drawing lines between points that are projected in the opposite sides. I wonder if d3.js-celestial has any function to solve that problem (milky way is quite similar and it works perfectly but is not a rectangle).

Thank you very much for your help!!

**Comment by ofrohn** [comment]
The problem is that you are using a symbol object to draw the line. Symbols are only good for small objects drawn on the map as a point and aren't equipped with the functionality to deal with projection issues necessary for larger objects covering whole regions.

You can use the summer triangle demo https://github.com/ofrohn/d3-celestial/blob/master/demo/triangle.html as a model how to do the equatorial box. Just adapt the jsonLine object with a geometry of type=polygon and provide the border points as an array. Which you already have in pos[] i think. 

What you want is basically a region +/- 10 degrees from the equator, correct? To have those lines drawn straight and not curved by projection you need to provide a point every 10 degrees or so. In for-loops:
```js
var pos = [];  
for (let i = -180; i <= 180; i+=10) pos.push([i, 10]);
for (let i = 180; i >= -180; i-=10) pos.push([i, -10]);
pos.push([-180, 10]);
```
And adapt the lineStyle and textStyle to your liking. Drop the Celestial.context.stroke() if you only want a region without an outline.

**Comment by roquasr** [comment]
Thank you very much! Now, everything works!

![antisolarShadow+geoBelt](https://user-images.githubusercontent.com/48351646/60097374-8d499400-9753-11e9-8d8b-6b2eabf242c5.jpeg)

Keep going with the project! It is really good.
