### ISSUE TITLE
Add shapes (like asterisms) but keep them in place as stars animate - for horizon or measurement tools

### ISSUE THREAD

**Issue by dcdigit** [ofrohn/d3-celestial#37]
Hi!

I am making great progress learning this wonderful toolkit. I am able to create custom shapes following the asterism demo.

However,  I would like to create a shape that stays fixed in place while the stars move independently. I am not sure how to do this with d3-celestial.

The idea is to have an indicator of horizon (like a planisphere window) maybe with some tree shapes or building shapes that mimic my local viewing area. Also, I would like to have a fixed measurement line overlaid in the sky.

Can you point me in the right direction? is there a demo code or a hidden "layers" function that would allow me to use the Lat, Lon coordinates, but keep them fixed as the stars and planets move?

Cheers!
Daniel

**Comment by ofrohn** [comment]
The Celestial.zenith() function gives you the overhead point for a given time and location.
A 90° circle around it would give you a pretty good horizon line, there´s a d3 function for that. And then draw stuff on that line as you like.
