### ISSUE TITLE
Preview of Wall Map

### ISSUE THREAD

**Issue by paperanniversary** [ofrohn/d3-celestial#38]
Can't wait to use this! I'm trying to view the preview of the Wall Map: http://ofrohn.github.io/celestial-demo/wallmap.html

But don't see anything. Is this link dead? Trying to see if the resulting image can be downloaded as Vector image. 

Thank you to anybody who can help me.

**Comment by ofrohn** [comment]
It is a very large map suitable for printing, therefore it needs a very long loading time, and try to scroll down and to the right to see anything besides white background.
