### ISSUE TITLE
Is div with id "celestial-form" actually required not optional?

### ISSUE THREAD

**Issue by DJWalker42** [ofrohn/d3-celestial#45]
Readme document reads that the div with "celestial-form" id is optional but it appears not to be. I get uncaught exceptions in javascript if I don't include a div with this id regardless of the boolean values set in the config namely, 'form' and 'location'.

This is the console log error:
```
celestial.js:3591 Uncaught TypeError: Cannot read property 'value' of null
    at daySel (celestial.js:3591)
    at new datetimepicker (celestial.js:3585)
    at geo (celestial.js:2420)
    at Object.Celestial.display (celestial.js:106)
    at example.html:178
```

**Comment by ofrohn** [comment]
It is required when you set form:true in the config, that behavior will change shortly to autegenerate a needed form tag if not present

**Comment by MichalZalecki** [comment]
I think it kinda is required even with `form: false`. `Celestial.display` is going to fire `geo()`. I need it as it defines `Celestial.skyview`. The problem is that the first line of `geo` also `d3.select("#celestial-form")`.

**Comment by ofrohn** [comment]
I think I have cleaned up that mess now, `geo()` get always called, and the form autocreated when it doesn't exist, When `form=false`, it isn't shown, but  all the functions are available.
Additionally, with the form visible, there is a finer grained possibility to decide what is shown, with the configuration settings `
formFields:  
   {"location": true, 
   "general": true,
   "stars": true,
   "dsos": true,
   "constellations": true, 
   "lines": true, 
   "other": true}`
 where setting each value to false makes the respective group of form fields invisible.
