### ISSUE TITLE
Visualization on the server side

### ISSUE THREAD

**Issue by eugenekoan** [ofrohn/d3-celestial#46]
Hi there,

Any ideas on running server side D3-Celestial rendering using Node JS? Is it possible?

**Comment by ofrohn** [comment]
You can possibly generate the canvas in-memory and deliver it as an image.
I did that for a browser here https://bit.ly/2rqeyAw
but have no experience doing it server-side, sorry

**Comment by umutesen** [comment]
The link is not working

**Comment by dewpboer** [comment]
Hello eugenekoan,

We approached this issue in the following way:
We downloaded Puppetteer through NPM.
We start the puppeteer browser, there we navigatie  to an a webpage where we render D3 celestial.

Then we take a screenshot of the div where the D3 celestial is located in and turn it into a pdf.

We didn't need to stream is back to the browser.

This approach takes between 10 - 15 seconds in total to start puppeteer and render everything.

**Comment by ofrohn** [comment]
I plan to provide a function which allows a headless setup, to get the JSON data for a given configuration without display. If you still follow this, would that help you?

**Comment by abisewski** [comment]
> I plan to provide a function which allows a headless setup, to get the JSON data for a given configuration without display. If you still follow this, would that help you?

Would be great!

**Comment by ofrohn** [comment]
The app has reached a state where it is difficult to add features without breaking something else. So I won't, apart from error corrections.
When I find the time, I'll  do a rewrite, probably with the latest version of d3. It will be announced in the readme when it's ready.

**Comment by jpwsutton** [comment]
Appreciate this issue has been closed, but for anyone out there looking for a workaround that lets them generate SVGs from d3-celestial without a web browser, I've worked out a bit of a hack that's available in this gist: https://gist.github.com/jpwsutton/f9e5ae50cbc3f8a2cc2a53d56b902a3a

Hopefully it's of some help to others!
