### ISSUE TITLE
How to set GMT?

### ISSUE THREAD

**Issue by kefio** [ofrohn/d3-celestial#48]
Hi, 
first of all thank you so much for this library!

I saw that in the celestial-form you can set the GMT.
Same time of the day with a different GMT have different star positions. 

Is it possible to set the GMT from code?

**Comment by ofrohn** [comment]
With GMT I think you mean the time zone. That was only possible via the form in earlier versions, the latest (0.6.18) allows setting the time zone via Celestial.date() and Celestial.skyview(). See documentation on home page
