### ISSUE TITLE
Can the constellation design be changed?

### ISSUE THREAD

**Issue by VictorMonroyHz** [ofrohn/d3-celestial#49]
Example:

Libra:
https://es.wikipedia.org/wiki/Libra_(constelación)
http://www.astroyciencia.com/2007/02/17/historia-de-la-constelacion-de-libra/

**Comment by ofrohn** [comment]
The constellation lines are determined by the file https://github.com/ofrohn/d3-celestial/blob/master/data/constellations.lines.json in the data folder, the format is defined in the readme.md for that folder, so by replacing that file you can adopt any kind of design you like.
