### ISSUE TITLE
Use Geo-Polygon projections

### ISSUE THREAD

**Issue by mr-deamon** [ofrohn/d3-celestial#50]
Hi
I am currently trying to implement https://github.com/d3/d3-geo-polygon as projections, but the process seems to be different than with the default d3-projections. Do you have any idea how i could achieve this? Will it change the whole part of executing the projection?

Chris

**Comment by ofrohn** [comment]
Those are implemented in d3 version 4+, I'm still using v3, the effort to bump to a new version is rather non-trivial, so it'll take some time yet. 
sorry

**Comment by mr-deamon** [comment]
Thanks for your response, i did not notice that difference. I might see if there is an "old" version of that polygon-plugin in order to get "your" sky projected on a dodecahedron :)

Thanks & have a good day
