### ISSUE TITLE
Help for new constellation

### ISSUE THREAD

**Issue by kiger** [ofrohn/d3-celestial#55]
Hi!

I'm trying to add the ancient chinese constellations, but i've stuck, i've manage to add the near equator ones but near the pole i cannot determine the transformation. For example there is the boundary line of the Draco constellation, I cannot make the transformation with Corel Draw.
Can you help me, that what app you use for the drawing?

Thank you
![image](https://user-images.githubusercontent.com/2277562/73008131-318cd980-3e0e-11ea-9711-dc22f33f5267.png)

**Comment by ofrohn** [comment]
I use the d3.js graphic library, which does all the transformation work for me. Unfortunately you'll have to do some scripting, or replace the provided constellation files in the data folder, which also provides the format specification. Data for Chinese constellations is provided e.g. by Stellarium https://github.com/Stellarium/stellarium/tree/master/skycultures/chinese.  

The good news is I have already planned to add the possibility to display constellations from different cultures, so I might do the necessary transformation scripts soon. Do you speak Chinese? You could maybe help me with checking the names.

**Comment by ofrohn** [comment]
I've now implemented the option to display entirely different constellations. See here for traditional Chinese constellations 
http://armchairastronautics.blogspot.com/2020/03/d3-celestial-chinese-constellations.html
