### ISSUE TITLE
Celestial.add example

### ISSUE THREAD

**Issue by mcoughlin** [ofrohn/d3-celestial#6]
Would it be possible to add a (non-json based) example of using Celestial.add to the documentation? For example, a white polygon on top of the map.html example?

**Comment by puziip** [comment]
Hi I agree - an example would be great. I have been trying for a couple hours to get it working but no joy so far. Would be greatly appreciated. I would like to plot a comet track over it.

Look forward to an example!

Thanks
P.

**Comment by ofrohn** [comment]
Well, json is pretty much the required data format, but I have added a howto section to the readme with an example of adding data with a json-object defined in the code. The full example is at demo/triangle.html. Hope that helps a bit.

You could of course also import whatever data you nedd with e.g. d3.csv() and generate the json on the fly from that. Tell me if you want an example for that.

**Comment by puziip** [comment]
Again, many thanks Olaf! I can now plot a comet track on the projections (haven't checked it all yet). I was getting stuck with the callback and redraw functions. At the moment I can generate JSON myself but if I need another example I will let you know!

**Comment by puziip** [comment]
Hi - I did not want to start another thread so I thought this was appropriate as it is related to the addition of data. I have successfully added a comet track on the projection. What would be even more useful is if I can label points along the track to show e.g. dates for when that comet is there. Is this currently possible?
Thanks

**Comment by ofrohn** [comment]
The function 
``Celestial.context.fillText(string, x, y);``
does what you need to, I think. You'd likely loop through a date range for the comet position, so in the loop that does the drawing, so at appropriate intervals put the text on the current position (+offset) like it is shown in the HowTo-section in the readme.md for the redraw-function.
Or if want to draw markers, Celestial.context exposes al of the [canvas functions](http://bucephalus.org/text/CanvasHandbook/CanvasHandbook.html), draw whatever you please.

**Comment by puziip** [comment]
Thanks. I have got something working roughly with Celestial.context.fillText(string, x, y) - and the example you did in the readme for adding extra data for the redraw function has now been useful to me twice! Many thanks. Depending on how I progress I may use the canvas functions.
