### ISSUE TITLE
Filling background doesn't work in Safari.

### ISSUE THREAD

**Issue by dewpboer** [ofrohn/d3-celestial#60]
Dear community,

Filling the background works for us in every browser.
In safari the background just stays transparent.
We tried it with RGB and HEX, in both cases the background stays transparent.

I attached 2 screenshots to display what's happening.
In one screenshot you see a pink background, and the stars are visible.
In the other screenshot the background, is white but it should be pink. The outline fill of the map does change to pink.

I also attached two screenshots made in chrome so you can see that other browsers don't have this behaviour.

Safari:
<img width="603" alt="Screen Shot 2020-02-19 at 11 58 24 AM" src="https://user-images.githubusercontent.com/53113636/74828329-39597400-530f-11ea-9a8e-310daafda43b.png">

<img width="644" alt="Screen Shot 2020-02-19 at 11 58 40 AM" src="https://user-images.githubusercontent.com/53113636/74828314-33639300-530f-11ea-9510-83bb821e8589.png">

Chrome:
<img width="627" alt="Screen Shot 2020-02-19 at 12 01 52 PM" src="https://user-images.githubusercontent.com/53113636/74828695-d87e6b80-530f-11ea-8c46-53f11d385b04.png">
<img width="601" alt="Screen Shot 2020-02-19 at 12 01 27 PM" src="https://user-images.githubusercontent.com/53113636/74828703-dcaa8900-530f-11ea-8c7f-fda006488742.png">

**Comment by ofrohn** [comment]
Can you check if you have the latest version 0.6.23?
Because I did some work last week to fix exactly this problem (see closed issues #7 & #25) and I hope it stays fixed.

**Comment by dewpboer** [comment]
@ofrohn I can confirm this is fixed after updating to the latest version!

**Comment by ofrohn** [comment]
Sweet!
