### ISSUE TITLE
Milky Way color inverts when alternate coordinates selected

### ISSUE THREAD

**Issue by ehdorrii** [ofrohn/d3-celestial#61]
When the coordinate system is changed, the Milky Way color seems to invert. Apparently that's not really what happens, but that's the effect. The behavior is the same in Chrome, Firefox and Edge.

To replicate this issue, just go to the interactive demo on GitHub, and change the coordinate system to ecliptic. Change back to equatorial and the MW remains white. Changing the MW parameters (color and opacity) points to the background color not being painted in the MW region.

**Comment by ofrohn** [comment]
OK, there was a slight error in the recent refactoring. It was the background fill. Should be OK now (v. 0.6.24). Can you check?

**Comment by ofrohn** [comment]
And now it also works in hemispheric maps (v. 0,6.25)

**Comment by ehdorrii** [comment]
Yes, the issue is resolved. Thank you for the rapid response! (And thanks for the fix to hemispheric -- I am using the orthographic projection exclusively.)

**Comment by ofrohn** [comment]
Yeah it is a very nice projection, especially when it spins!
