### ISSUE TITLE
How-to question: determine current FOV center

### ISSUE THREAD

**Issue by ehdorrii** [ofrohn/d3-celestial#62]
I've zoomed in on a section of sky, and then panned to a particular view. How can I retrieve the central coordinates of the location I'm now viewing? The coordinate system I'm using is ecliptic -- do I need to do a transformation to the ecliptic coordinate system?  I've spent significant time researching this, and haven't found a solution. (i.e. I'm not just being lazy. Stupid maybe, but not lazy.)

**Comment by ofrohn** [comment]
If you call Celestial.rotate() without parameters, it returns the current center coordinates. I think that is what you are looking for.

**Comment by ehdorrii** [comment]
I believe it is! I figured it would be simple -- but it would have taken me a long time before I tried Celestial.rotate().  Thank you again.
