### ISSUE TITLE
Perspective projection

### ISSUE THREAD

**Issue by jdarpinian** [ofrohn/d3-celestial#67]
I'd like to display the stars as if they were seen from a camera pointed up about 45 degrees from the horizon. I don't see how to do that with any of the available projections. Do I need to make a new one?

**Comment by ofrohn** [comment]
I think the orthographic projection is what  you are looking for. It distorts the view in much the same way as a fish eye- or wide-angle lens, depending on your viewing angle. I assume you'd want a wide view, because for small angles distortion doesn't really matter. 
You might be interested in this demo that tries to display stars as they appear in the sky.

**Comment by jdarpinian** [comment]
Thanks, I like that demo! I think orthographic is close to what I want, but I don't see a built in way to rotate the view so that the local zenith is pointing up. Did I miss it? Would the correct way to implement this be to add a "horizon" coordinate system in transform.js?

**Comment by ofrohn** [comment]
Well, I'm afraid I didn't yet get around to implement azimuth/altitude coordinates, with horizon viewport, but it's on the (https://github.com/ofrohn/d3-celestial/wiki/Roadmap)[roadmap].

All I can offer right now is  ```Celestial.skyview({geolocation, date})``` (see readme documentation), that gives the hemispheric view from a specific location at a specific time, with the zenith at the center, if you zoom in and rotate 45 degrees down, you'll get (-ish) the view  you want.

**Comment by jdarpinian** [comment]
Oh cool, I'll look forward to that. I ended up using VirtualSky instead because I found it easier to add horizon coordinates to it, but the rendering isn't as nice. The integration is live on https://james.darpinian.com/satellites/ if you want to see what the application looks like. I'll look into replacing VirtualSky with d3-celestial when horizon coordinates are implemented.

**Comment by ofrohn** [comment]
Ah, very nice app! I'll see when I get around to it
