### ISSUE TITLE
Svg problem with stars

### ISSUE THREAD

**Issue by 4actuaries** [ofrohn/d3-celestial#70]
HI ofrohn,

i want to download svg image with white stars only but there is problem when i download the svg map 
with white stars its show blank image

![Screenshot from 2020-05-13 10-35-46](https://user-images.githubusercontent.com/60430284/81773295-a1ca8280-9505-11ea-9c10-051d5ff439f6.png)
![Screenshot from 2020-05-13 10-35-58](https://user-images.githubusercontent.com/60430284/81773300-a42cdc80-9505-11ea-8823-a84137aef2ae.png)

**Comment by tech-striker** [comment]
yes i have same problem

**Comment by ofrohn** [comment]
The stars were there, but they were displayed black-on-black, which I'll admit isn't very useful.
Should be fixed now!
