### ISSUE TITLE
SVG problem

### ISSUE THREAD

**Issue by abisewski** [ofrohn/d3-celestial#71]
Hi!

First of all, thanks/congratz for the awesome work! This lib is awesome!

Second, maybe I founded two issues on svg save.

The first one is about specific dates/locations. After SVG save the MW overlaying almost all the map.
You can check this setting up here https://ofrohn.github.io/celestial-demo/viewer.html

`projection: "stereographic"
latitude: -23
longitude: -46
datetime: 2020-06-14 07:20:00 −0300`

You'll see that on preview is everything is right, but after svg save the MW overlay the map.
https://imgur.com/IkxNwdK

--

Other thing its about a line that appears even if all lines its disabled

You can check on this another print:
https://imgur.com/KSTEYuF

--

Thats all!
Thanks guys!

**Comment by ofrohn** [comment]
OK, this again. I already had that problem with canvas, but thought it wouldn't occur in svg. Apparently, no such luck. OTOH I already know how to fix it, so I just did. The one with the Milkyway. The other one I couldn't replicate, but it may be fixed with this update as well.
Could you check, please?

**Comment by abisewski** [comment]
OMG! This was very fast! Thanks!

Second issue has not been fixed :/

You can replicate on this way:

- https://ofrohn.github.io/celestial-demo/viewer.html
- `latitude: -40`
- `longitude: 0`
- `datetime: 2020-05-18 15:23:02 −0300`
- `background color: #fff`

Result is here: https://imgur.com/8hqWwTd

You'll see a black line crossing vertically

**Comment by ofrohn** [comment]
OK, now I see it, that's the wrong kind of outline, plus the wrongly styled Milkyway fix.
 Should be fixed now.

**Comment by abisewski** [comment]
Nice! Thanks a lot @ofrohn !

You're awesome!
