### ISSUE TITLE
How to disable animations?

### ISSUE THREAD

**Issue by umutesen** [ofrohn/d3-celestial#72]
I am looking for a way to disable all animations for skyview operation. 

I tried below with no luck, is there a configuration option to disable animations?

```
function flushAllD3Transitions() {
    var now = Date.now;
    Date.now = function() { return Infinity; };
    d3.timer.flush();
    Date.now = now;
 }
```

**Comment by ofrohn** [comment]
The skyview function has the purpose move the map to a view at a certain time and/or location. So you managed to prove that the function is quite robust ;)
The trick to disable animations is to set follow:"center" in the config, that way the map will always be centered on the coordinates you give it with the center setting. So ```Celestial.reload({follow:"center", center: [lon, lat]})``` is the way to go.

**Comment by umutesen** [comment]
Thank you for your response. I tried running the following in the inspector console on https://ofrohn.github.io/celestial-demo/map.html

`
Celestial.reload({follow:'center', center: [51.5285578, -0.2420246]})
`

The map does not change location?

**Comment by umutesen** [comment]
It looks like transform must be passed in:

`Celestial.reload({center: [1.5285578, -0.2420246], follow:'center', transform: 'equatorial'})`

The map just flashes when this is executed and does not change.

**Comment by ofrohn** [comment]
Well I should read my own code before giving advice! reload was indeed only accepting transform as a setting. I'll file that under 'WTH did I do that?' There's no reason why one shouldn't be able to reload for any parameter.

Secondly, I had indeed no way to change orientation without animated rotation, so I changed that, and reload is just the place to do it. So with the latest version the above code should work now.

**Comment by umutesen** [comment]
Thanks, I'll give that a shot! Is the latest version on npm?

**Comment by ofrohn** [comment]
It is now

**Comment by umutesen** [comment]
Thanks, it is now changing location. does reload take date change into consideration?

e.g. 
```
      Celestial.date(date);

      Celestial.reload({
        center: [config.lng, config.lat],
        transform: 'equatorial'
      });
```

**Comment by ofrohn** [comment]
It does. If you set follow to "center", however, it doesn't follow the zenith - which changes with the date - so only the planetary positions change.
If follow is set to "zenith", it should reflect the date change, and actually dies that in the latest version.

**Comment by ofrohn** [comment]
Note: Celestial.date(date); already does a redraw,

**Comment by umutesen** [comment]
date change is reflected when following zenith, however, it still animates like the skyview. I was hoping to turn off animations while setting location and date. 

I find that the animations are a lot faster (close to off) when I change the duration in code:

  `ANIMINTERVAL_R = 200`

Not sure if this is best way to handle it though.

**Comment by ofrohn** [comment]
Now reload also jumps when following zenith, thus reflecting date or location changes, without animation.
