### ISSUE TITLE
Stars going outside canvas and svg

### ISSUE THREAD

**Issue by kgoyal000** [ofrohn/d3-celestial#78]
Hello ofrohn , i figured out some stars are getting out of frame , is there a way to fix them?

![IMG_20200614_184224](https://user-images.githubusercontent.com/62390711/84594369-6eb24080-ae6f-11ea-8a65-a482d38bbd93.jpg)

Also check moon
![d3-celestial20200414T000100+0530](https://user-images.githubusercontent.com/62390711/84594559-ca30fe00-ae70-11ea-8ab6-d5ca4ffbdb96.png)

Thanks

**Comment by ofrohn** [comment]
You could make the border the same color as the background, and wide enough to accommodate the maximum symbol size. Under background -> stroke and width in the config
Other than that I could only clip the region outside the map, but then the symbols are cut in half when near the border, which I think is also not very good, and it would also clip any text that overlaps the border, so I would only implement that when I have that problem fixed.

**Comment by kgoyal000** [comment]
Is there a way to decrease map radius than whole circle?
