### ISSUE TITLE
Dash ecliptic override constellations line style

### ISSUE THREAD

**Issue by qubiack** [ofrohn/d3-celestial#83]
I think I found an error in this amazing app. If you set a:
```
lines: {
    ecliptic: {
         ....,
         dash: [5, 5],
     ....
```
This override also `constellations.lineStyle.dash` but this can't be set by property in configuration panel.

**Comment by ofrohn** [comment]
That was probably because it was impossible to set the line dash style on constellation lines. That is fixed now, Please check

**Comment by qubiack** [comment]
Thanks for quick response 👍  

In NPM it's still version 0.7.25 so I can't check this change right now. But I can wait - it's not a huge problem for me :) 

Could you give me tips on how could I recalculate location (geolocation for example for Berlin) to Center coordinates? Is any function available for that? I See that If I use Equatorial i can copy one value, but how can I recalculate another?

**Comment by ofrohn** [comment]
The current version is now on npm. sorry for the delay.

**Comment by qubiack** [comment]
Thanks @ofrohn . I will test it today:)

Could you respond to another question?

**Comment by qubiack** [comment]
@ofrohn I confirm - this fix work properly so we can close this issue 👍 

Could you give me tips on how could I recalculate location (geolocation for example for Berlin) to Center coordinates? Is any function available for that? I See that If I use Equatorial I can copy one value, but how can I recalculate another?

**Comment by ofrohn** [comment]
I#m not sure I understand your question. You can set the terrestrial geolocation for a certain place and a time with the skyview function, and then get the celestial center coordinates, i.e. the equatorial coordinates directly above at that time with ```Celestial.zenith()```. Does that help?

**Comment by qubiack** [comment]
I see that you just fix this and in version `0.7.26` when I set a `geopos` it's recalculated into the center just after loading.

I think that I my problems can be solved by disable all animation & add a callback to end of the redraw process. Can I prepare PR for that?

**Comment by qubiack** [comment]
OK - I prepare some changes on my branch:
https://github.com/ofrohn/d3-celestial/pull/84/files

Do you want anything from these changes or I should do it all on my fork branch without sharing it?

**Comment by ofrohn** [comment]
You can avoid animations by updating the view with ```Celestial.reload(config)``` where config can contain anything configurable as an object.
You can also use a callback function by defining an anonymous via ```Celestial.addCallback()```

**Comment by ofrohn** [comment]
Oops, crosspost! I'll check what you did and we'll see
