### ISSUE TITLE
Moon under stars

### ISSUE THREAD

**Issue by abisewski** [ofrohn/d3-celestial#89]
Hi there!

Do you guys have any idea why my moon is under stars as you can see [here](https://imgur.com/6M41EV3)? There is any configuration to fix this?

Thanks guys!

**Comment by qubiack** [comment]
In my fork, I change moon in "disc" type to be displayed as a disk without `opacity`

**Comment by abisewski** [comment]
Thanks for you answer!

I updated my repository and was fixed on june of this year.
