### ISSUE TITLE
canvas style in celestial.css is applied to every canvas tag

### ISSUE THREAD

**Issue by Leofaber** [ofrohn/d3-celestial#9]
Hi, 
the style for canvas defined in celestial.css

canvas { display: inline-block; position:absolute; z-index:0; cursor:hand; cursor:grab; cursor:-moz-grab; cursor:-webkit-grab; }
canvas:active { cursor:move; cursor: grabbing; cursor: -moz-grabbing; cursor: -webkit-grabbing; }

affects every canvas element in the web page, in particular it ovverrides the canvas properties of another js library I am using. 

I think that a possibile fix could be adding a canvas-class to the canvas selector in order to apply that style only to canvas elements of that class. Something like: 
canvas.canvas-class { display: inline-block; position:absolute; z-index:0; cursor:hand; cursor:grab; cursor:-moz-grab; cursor:-webkit-grab; }

Thank you!

**Comment by ofrohn** [comment]
D'oh! That was as stupid as it was easy to fix. 
canvas was already inside an id'ed div so #d3-celestial canvas { ... } does the trick.
Check the lates version, please, should work non-obnoxious now!

**Comment by Leofaber** [comment]
Yeah now it's working. 
Thank you!
