### ISSUE TITLE
mw.json is loaded even when mw:{show:false} in config

### ISSUE THREAD

**Issue by oudeicrat** [ofrohn/d3-celestial#98]
why is mw.json loaded even when the config says `mw:{show:false}` ? A similar problem is with some other json files like constellations.border.json, dsos.bright.json, dsonames.json etc

**Comment by ofrohn** [comment]
That is not a bug but a feature, because you might decide to show the Milky Way after loading, therefore everything is loaded at the start and then easily switchable.
